# Generated by Django 3.1.13 on 2021-11-02 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre conjunto de datos, Use su nomenclatura')),
                ('Image_instruccions', models.ImageField(upload_to='experimentos/instructions', verbose_name='Imagen con instrucciones')),
                ('disclaimer', models.TextField(blank=True, verbose_name='Pegue aca su disclaimer y de estilos.')),
                ('survey_url', models.URLField(verbose_name='URL Encuesta desde google forms, la url DEBE recibir un ID')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='set_relation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='experimentos.set'),
            preserve_default=False,
        ),
    ]
